[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "acs"
version = "0.4.2"
description = "Lightweight distributed computing system"
requires-python = ">=3.11"
dependencies = [
    "typer",
]

[project.scripts]
acs = "cli.cli:app"

[tool.setuptools.packages.find]
include = [
    "acs*",
    "machines*",
    "langs*",
    "cli*"
]
exclude = ["node_modules*"]