[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "acs"
version = "0.5.8"
description = "Lightweight distributed computing system"
requires-python = ">=3.12"
dependencies = [
	"fastapi",
	"uvicorn",
	"pydantic",
	"zeroconf",
	"langchain_sandbox",
	"typer",
	"python-dotenv",
	"jinja2"
]

[project.scripts]
acs = "cli.cli:app"

[tool.setuptools.packages.find]
include = [
    "acs*",
    "machines*",
    "langs*",
    "cli*",
    "data*",
    "HTML*"
]
exclude = ["node_modules*"]

[tool.setuptools.package-data]
data = ["*.json", "*.db", "secrets/.env"]
